[package]
name = "curlx"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
description = "curl wrapper with templating, bookmarking and environments powers just like postman"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
license-file = "LICENSE"
include = ["src/**/*", "LICENSE", "*.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
console = "0.15"
dialoguer = "0.10"
liquid = "0.26"
liquid-core = "0.26"
regex = "1.5"
serde = "1.0"
tempfile = "3.3"
thiserror = "1.0"
toml = "0.5"
walkdir = "2.3"
